# Generated by Django 2.1.5 on 2019-03-13 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import events_manager.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLocality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fecha De Creación')),
                ('capacity', models.IntegerField(default=0, validators=[events_manager.core.validators.validator_greater_zero], verbose_name='Capacidad')),
                ('price', models.FloatField(default=0, validators=[events_manager.core.validators.validator_greater_zero], verbose_name='Capacidad')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.Event', verbose_name='Evento')),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locality', to='event.Event', verbose_name='Localidad')),
                ('user_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
