# Generated by Django 2.1.5 on 2019-02-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identification',
            field=models.CharField(default='', max_length=40, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('Asesor', 'Asesor'), ('Odontologo', 'Odontologo')], max_length=100, null=True, verbose_name='Cargo'),
        ),
    ]
