# Generated by Django 2.1.5 on 2019-02-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190205_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('Vendedor', 'Vendedor'), ('Cliente', 'Cliente'), ('Administrador Del Sistema', 'Administrador Del Sistema'), ('Gerente', 'Gerente')], max_length=100, null=True, verbose_name='Rol'),
        ),
    ]
