# Generated by Django 2.1.5 on 2019-02-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190222_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desactiva el acceso al usuario a las caracteristicas del sistema', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('Gerente', 'Gerente'), ('Administrador Del Sistema', 'Administrador Del Sistema'), ('Vendedor', 'Vendedor'), ('Cliente', 'Cliente')], max_length=100, null=True, verbose_name='Rol'),
        ),
    ]
