# Generated by Django 2.1.5 on 2019-02-27 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190222_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_report', 'Can View Report Module')]},
        ),
    ]
