# Generated by Django 2.1.5 on 2019-03-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeevent',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Nombre'),
        ),
    ]
