# Generated by Django 2.1.5 on 2019-03-16 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('type_event', '0005_auto_20190315_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeevent',
            name='user_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
    ]
