# Generated by Django 2.1.5 on 2019-03-16 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0003_auto_20190315_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='user_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
    ]
