# Generated by Django 2.1.5 on 2019-02-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('event_type', models.CharField(choices=[('concierto', 'Concierto'), ('cultural', 'Cultural'), ('deportivo', 'Deportivo'), ('clerico', 'Clerico')], max_length=250, verbose_name='Tipo')),
                ('capacity', models.IntegerField(verbose_name='Capacidad')),
                ('date', models.DateField(verbose_name='Fecha')),
            ],
        ),
    ]
