# Generated by Django 2.1.5 on 2019-02-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Futbol', 'Futbol'), ('Tenis ', 'Tenis '), ('Béisbol', 'Béisbol')], max_length=250, verbose_name='Tipo'),
        ),
    ]
