# Generated by Django 2.1.5 on 2019-03-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ready_for_sale',
            field=models.BooleanField(default=False, verbose_name='Listo Para Vender'),
        ),
    ]
