# Generated by Django 2.1.5 on 2019-03-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_ready_for_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_card',
            field=models.ImageField(default='event_images/no_image/default_image.jpg', upload_to='event_images/'),
        ),
    ]
