# Generated by Django 2.1.5 on 2019-02-23 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190222_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cupos_restantes',
            field=models.IntegerField(default=0, verbose_name='Cupos Restantes'),
        ),
        migrations.AddField(
            model_name='event',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='event',
            name='division',
            field=models.CharField(choices=[('Primera', 'Primera'), ('Segunda ', 'Segunda '), ('Tercera', 'Tercera')], max_length=250, null=True, verbose_name='Division'),
        ),
        migrations.AddField(
            model_name='event',
            name='equipo_local',
            field=models.CharField(max_length=250, null=True, verbose_name='Equipo Local'),
        ),
        migrations.AddField(
            model_name='event',
            name='equipo_visitante',
            field=models.CharField(max_length=250, null=True, verbose_name='Equipo Visitante'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
