# Generated by Django 2.1.5 on 2019-02-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20190222_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='precio_ticket',
            field=models.IntegerField(default=0, verbose_name='Precio Boleto'),
        ),
    ]
