# Generated by Django 2.1.5 on 2019-03-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_image_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_card',
            field=models.ImageField(default='event_images/default_image.png', upload_to='event_images/', verbose_name='Imagen Evento'),
        ),
    ]
