# Generated by Django 2.1.5 on 2019-02-07 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ticket', to='event.Event')),
            ],
        ),
    ]
