# Generated by Django 2.1.5 on 2019-03-13 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import events_manager.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_locality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fecha De Creación')),
                ('price', models.FloatField(default=0, validators=[events_manager.core.validators.validator_greater_zero], verbose_name='Precio')),
                ('tax', models.FloatField(default=0, validators=[events_manager.core.validators.validator_greater_zero], verbose_name='Impuesto')),
                ('quantity', models.IntegerField(default=0, validators=[events_manager.core.validators.validator_greater_zero], verbose_name='Cantidad')),
                ('subtotal', models.FloatField(default=0, validators=[events_manager.core.validators.validator_greater_zero], verbose_name='Subtotal')),
                ('total', models.FloatField(default=0, validators=[events_manager.core.validators.validator_greater_zero], verbose_name='Total')),
                ('event_locality', models.ForeignKey(error_messages={'blank': 'El Campo No Puede Estar En Blanco', 'invalid': 'El Valor No Es Valido', 'invalid_choice': 'Opcion No Valida', 'unique': 'El Ticket Debe Ser Unico'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_locality', to='event_locality.EventLocality', verbose_name='Localidad Evento')),
                ('receipt', models.ForeignKey(error_messages={'blank': 'El Campo No Puede Estar En Blanco', 'invalid': 'El Valor No Es Valido', 'invalid_choice': 'Opcion No Valida', 'unique': 'El Ticket Debe Ser Unico'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='receipt.Receipt', verbose_name='Factura')),
                ('user_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
            ],
            options={
                'permissions': [('view_own_ticket', 'Can View Only Own Tickets')],
            },
        ),
    ]
