# Generated by Django 2.1.5 on 2019-02-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_ticket_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='iva',
            field=models.FloatField(blank=True, null=True, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subtotal',
            field=models.FloatField(blank=True, null=True, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta Debido', 'Tarjeta Debido'), ('Credito', 'Credito')], default='Efectivo', error_messages={'blank': 'El Campo No Puede Estar En Blanco', 'invalid': 'El Valor No Es Valido', 'invalid_choice': 'Opcion No Valida', 'unique': 'El Ticket Debe Ser Unico'}, max_length=250, verbose_name='Metodo De Pago'),
        ),
    ]
